apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress

components:
  - ../components/mysql
  - ../components/dbconfig
  # - ../components/postgres
  # - ../components/redis

resources:
- wordpress
- namespace.yaml
