
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: mysql-secret
    envs:
      - secrets

generatorOptions:
  disableNameSuffixHash: true

images:
 - name: mariadb
   newName: mariadb
   newTag: 10.5.8

resources:
- deployment.yaml
- svc.yaml
