apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wordpress
  namespace: argocd
spec:
  description: "Proyecto para gestionar wordpress"
  destinations:
    - namespace: wordpress
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
