---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-app-istio
  namespace: argocd
spec:
  description: "sample app para istio"
  destinations:
    - namespace: sample-app-istio
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
