apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: istio-system
  namespace: argocd
spec:
  description: Proyecto para el stack de Istio y observabilidad
  sourceRepos:
    - https://istio-release.storage.googleapis.com/charts
    - https://jaegertracing.github.io/helm-charts
    - https://kiali.org/helm-charts
  destinations:
    - namespace: istio-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
