---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: istio-base
            chart: base
            repoURL: https://istio-release.storage.googleapis.com/charts
            revision: 1.25.2

          - name: istiod
            chart: istiod
            repoURL: https://istio-release.storage.googleapis.com/charts
            revision: 1.25.2

          - name: istio-ingressgateway
            chart: gateway
            repoURL: https://istio-release.storage.googleapis.com/charts
            revision: 1.25.2
            values: |
              service:
                type: LoadBalancer

          - name: jaeger
            chart: jaeger-all-in-one
            repoURL: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/charts
            revision: 0.1.12

          - name: kiali-operator
            chart: kiali-operator
            repoURL: https://kiali.org/helm-charts
            revision: 1.84.0
            values: |
              cr:
                create: true
                namespace: istio-system

  template:
    metadata:
      name: '{{name}}'
    spec:
      project: istio-system
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{revision}}'
        helm:
          releaseName: '{{name}}'
          {{- if .values }}
          values: |
            {{ .values | nindent 12 }}
          {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
