apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: istio-base
            chart: base
            revision: 1.25.2
            repoURL: https://istio-release.storage.googleapis.com/charts

          - name: istiod
            chart: istiod
            revision: 1.25.2
            repoURL: https://istio-release.storage.googleapis.com/charts

          - name: istio-ingressgateway
            chart: gateway
            revision: 1.25.2
            repoURL: https://istio-release.storage.googleapis.com/charts
            values: |
              service:
                type: LoadBalancer

  template:
    metadata:
      name: '{{name}}'
    spec:
      project: istio-system
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{revision}}'
        helm:
          releaseName: '{{name}}'
          values: '{{values}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true
