apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  project: istio-system
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    helm:
      releaseName: istiod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true