apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: istio-system
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istio-base
    targetRevision: 1.25.2  # La versión que necesites
    helm:
      releaseName: istio-base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
