apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
spec:
  project: istio-system
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.25.2    # Cambia a la versión de Istio que uses
    helm:
      releaseName: istio-ingressgateway
      values: |
        service:
          type: LoadBalancer  # o NodePort, depende de tu clúster
        labels:
          istio: ingressgateway
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
