apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: istio-base
            chart: base
            revision: 1.25.2
          - name: istiod
            chart: istiod
            revision: 1.25.2
          - name: istio-ingressgateway
            chart: gateway
            revision: 1.25.2
          # - name: jaeger
          #   chart: jaeger
          #   repoURL: https://jaegertracing.github.io/helm-charts
          #   revision: 0.71.13
          - name: kiali-operator
            chart: kiali-operator
            repoURL: https://kiali.org/helm-charts
            revision: 1.84.0
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: istio-system
      source:
        repoURL: '{{ if .repoURL }}{{ .repoURL }}{{ else }}https://istio-release.storage.googleapis.com/charts{{ end }}'
        chart: '{{chart}}'
        targetRevision: '{{revision}}'
        helm:
          releaseName: '{{name}}'
          values: |
            {{- if eq .name "istio-ingressgateway" }}
            service:
              type: LoadBalancer
            {{- end }}
            {{- if eq .name "kiali-operator" }}
            cr:
              create: true
              namespace: istio-system
            {{- end }}
            {{- if eq .name "jaeger" }}
            provisionDataStore:
              cassandra: false
              elasticsearch: false
            allInOne:
              enabled: true
            storage:
              type: memory
            {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
