apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example project used to demonstrate Declarative deployments in ArgoCD
  sourceRepos:
  - '*'
  destinations:
  - namespace: monitoring
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
