---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-istio
  namespace: argocd
spec:
  project: sample-app-istio
  source:
    repoURL: 'https://github.com/emalpb/cluster_up.git'
    path: kustomize/sample-app-istio/
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app-istio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true