apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onlineboutique
  namespace: onlineboutique
spec:
  chart:
    spec:
      chart: onlineboutique
      version: 0.3.7  # Asegurate de usar la versión correcta
      sourceRef:
        kind: HelmRepository
        name: onlineboutique-oci
        namespace: argocd
  interval: 5m
